env:
  region: 'ap-southeast-1'
  profile: 'gloco-bao.nguyen'
sns:
  token-topic-arn: 'arn:aws:sns:ap-southeast-1:336087288634:Notification-Device-Token'
  mg-fb-topic-arn: 'arn:aws:sns:ap-southeast-1:336087288634:Notification-Mongo-Firebase'
mongo:
  #uri: 'admin:FreeOneForTest@testcluster-ekqx9.mongodb.net?retryWrites=true'
  #db: 'test'
  uri: 'notification:EB3Lv22urEbw6uA@cluster0-cxlxt.mongodb.net?retryWrites=true'
  db: 'notification'

